---
- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Update and install required packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure prerequisites are installed for Docker Compose
      apt:
        name:
          - jq
        state: present

    - name: Get the latest Docker Compose version
      uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        return_content: yes
      register: compose_api_response

    - name: Parse the Docker Compose version
      set_fact:
        compose_version: "{{ compose_api_response.json.tag_name }}"

    - name: Get system architecture
      command: uname -m
      register: system_arch

    - name: Get operating system
      command: uname -s
      register: system_os

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ system_os.stdout }}-{{ system_arch.stdout }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      command: docker-compose --version

